# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TreyVisay' do
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'SwiftyJSON', '4.0.0'
  pod 'Charts', '3.2.2'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


  pod 'Firebase/Core', '~> 5.20.2'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNShare', :path => '../node_modules/react-native-share'

end

swift4 = ['Charts']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    target.build_configurations.each do |config|
        if swift4.include?(target.name)
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
  end
end
